### ISSUE TITLE
fixedCenter false problem

### ISSUE THREAD

**Issue by QitmentX7** [controlwear/virtual-joystick-android#16]
Hello, dear friend!
I want use your awesome library! And i need your help! Because I need the button not to return to the center.
I try attribute:
custom:JV_fixedCenter="false" 
joystick.setFixedCenter(false);
But it didn't work.
Great thanks in advanced for help!

**Comment by makowildcat** [comment]
Hello @QitmentX7 !
Thank you for feedback I will have a look quickly and fix it! (Probably this week-end)
I'll let you know !
Kindly,
Damien

**Comment by QitmentX7** [comment]
I'll be very grateful!!!

**Comment by makowildcat** [comment]
Hi @QitmentX7,

Sorry being late, had a couple of exams.
Did you try with the option AutoReCenterButton ? Set it to false.
`JV_autoReCenterButton="false"` or `joystick.setAutoReCenterButton(false);`

With this option the button won't be re-centered automatically. I think it is what you are looking for.
Be aware that if you use this option you should let the FixedCenter to default value (true) otherwise the behavior is a bit weird. You can try what suit you the best ;)

Let me know if it is correct.
Too bad that I did not have a better look before, I could have answered this much earlier, I'm sorry.

Kindly,

Damien

**Comment by QitmentX7** [comment]
Super it work!!! It's my fail I used the old version from github, and it function was not exist.
Great thanks friend! You're doing a really cool thing!

**Comment by makowildcat** [comment]
Great! :)
I should make a better documentation too!

I’ll close this issue.
