### ISSUE TITLE
Error:No resource identifier found for attribute 'roundIcon' in package 'android'

### ISSUE THREAD

**Issue by Lakemast** [controlwear/virtual-joystick-android#4]
![error](https://cloud.githubusercontent.com/assets/25143692/21971109/8902234e-db94-11e6-9828-6155cf5da04e.png)
Hello my friend,
I'm trying to use your library in Canary 2.3 beta and I'm getting this error:
Error:No resource identifier found for attribute 'roundIcon' in package 'android'
I'm a newbie in android, could you give a support on that issue?

Thanks in advance!

**Comment by makowildcat** [comment]
Hello @Lakemast 

I’m afraid but this error doesn’t seem to come from this library, there is nothing related to “roundIcon”. I just created a new app with Android Studio 2.3 beta 2, everything worked well.
Maybe, have a look on stackoverflow to find something similar/related.

Also, if you are a new to Android, except for specific needs, you'd better use the “Stable Channel” instead of “Canary Channel”, just in case.

Have a good day.

Kindly,

Damien

**Comment by Lakemast** [comment]
Thanks my friend @makowildcat !
